/**
 * Export chat conversation as a downloadable HTML report.
 * Uses a clean print-friendly layout that users can print to PDF
 * from their browser (Ctrl+P → Save as PDF).
 *
 * No external dependencies required.
 */

import type { ChatMessage } from '@/types'

export function exportChatAsReport(
  messages: ChatMessage[],
  workbookName: string,
): void {
  const conversationMessages = messages.filter(
    (m) => m.role === 'user' || (m.role === 'assistant' && m.content.trim().length > 0),
  )

  if (conversationMessages.length === 0) return

  const now = new Date()
  const dateStr = now.toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
  const timeStr = now.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' })

  const messagesHtml = conversationMessages
    .map((msg) => {
      const isUser = msg.role === 'user'
      const label = isUser ? 'You' : 'smartsh!t'
      const bgClass = isUser ? 'background:#eff6ff;border-left:3px solid #3b82f6;' : 'background:#f9fafb;border-left:3px solid #10b981;'
      const content = escapeHtml(msg.content)
        .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
        .replace(/\*(.+?)\*/g, '<em>$1</em>')
        .replace(/\n/g, '<br>')

      return `
        <div style="margin-bottom:16px;padding:12px 16px;border-radius:8px;${bgClass}">
          <div style="font-size:11px;font-weight:600;color:#64748b;margin-bottom:6px;">${label}</div>
          <div style="font-size:14px;line-height:1.6;color:#1e293b;">${content}</div>
        </div>`
    })
    .join('\n')

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>smartsh!t Report — ${escapeHtml(workbookName)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; max-width: 800px; margin: 0 auto; color: #1e293b; }
    @media print { body { padding: 20px; } .no-print { display: none; } }
    h1 { font-size: 24px; font-weight: 700; margin-bottom: 4px; }
    .meta { font-size: 13px; color: #64748b; margin-bottom: 24px; }
    .divider { border: none; border-top: 1px solid #e2e8f0; margin: 24px 0; }
    .footer { margin-top: 32px; font-size: 11px; color: #94a3b8; text-align: center; }
    .actions-btn { display: inline-block; margin-top: 16px; padding: 8px 16px; background: #1e293b; color: white; border-radius: 8px; font-size: 13px; cursor: pointer; border: none; }
    .actions-btn:hover { background: #334155; }
  </style>
</head>
<body>
  <h1>📊 Analysis Report</h1>
  <div class="meta">${escapeHtml(workbookName)} · ${dateStr} at ${timeStr}</div>
  <hr class="divider">
  ${messagesHtml}
  <hr class="divider">
  <div class="footer">Generated by smartsh!t · smartsht.com</div>
  <div class="no-print" style="text-align:center;margin-top:16px;">
    <button class="actions-btn" onclick="window.print()">Print / Save as PDF</button>
  </div>
</body>
</html>`

  // Open in a new tab for the user to print
  const blob = new Blob([html], { type: 'text/html' })
  const url = URL.createObjectURL(blob)
  window.open(url, '_blank')

  // Clean up after a delay
  setTimeout(() => URL.revokeObjectURL(url), 30_000)
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}
