// Category: Small Business — Accounting & Tax. Edit as data — no logic here.
import type { TemplateSpec } from './types';

export const smallBusinessAccountingTemplates: TemplateSpec[] = [
{
  "tool": "create_pnl_statement",
  "label": "pnl statement",
  "cells": {
    "A1": { "value": "Profit & Loss Statement" },
    "A2": { "value": "Period: __________" },
    "A4": { "value": "REVENUE" },
    "B4": { "value": "Amount" },
    "A5": { "value": "Product Sales" },
    "B5": { "value": 50000 },
    "A6": { "value": "Service Revenue" },
    "B6": { "value": 30000 },
    "A7": { "value": "Other Income" },
    "B7": { "value": 2000 },
    "A8": { "value": "Total Revenue" },
    "B8": { "value": null, "formula": "=SUM(B5:B7)" },
    "A10": { "value": "COST OF GOODS SOLD" },
    "A11": { "value": "Materials" },
    "B11": { "value": 15000 },
    "A12": { "value": "Direct Labor" },
    "B12": { "value": 12000 },
    "A13": { "value": "Total COGS" },
    "B13": { "value": null, "formula": "=SUM(B11:B12)" },
    "A15": { "value": "GROSS PROFIT" },
    "B15": { "value": null, "formula": "=B8-B13" },
    "A17": { "value": "OPERATING EXPENSES" },
    "A18": { "value": "Rent" },
    "B18": { "value": 3000 },
    "A19": { "value": "Utilities" },
    "B19": { "value": 500 },
    "A20": { "value": "Marketing" },
    "B20": { "value": 2000 },
    "A21": { "value": "Insurance" },
    "B21": { "value": 800 },
    "A22": { "value": "Total Expenses" },
    "B22": { "value": null, "formula": "=SUM(B18:B21)" },
    "A24": { "value": "NET INCOME" },
    "B24": { "value": null, "formula": "=B15-B22" }
  },
  "formats": [
    { "ids": ["A1"], "format": { "bold": true, "fontSize": 16, "fontColor": "#7C3AED" } },
    { "ids": ["A4", "A10", "A17", "B4"], "format": { "bold": true, "bgColor": "#EDE9FE" } },
    { "ids": ["A8"], "format": { "bold": true } },
    { "ids": ["B8"], "format": { "bold": true, "bgColor": "#EDE9FE" } },
    { "ids": ["A13"], "format": { "bold": true } },
    { "ids": ["A15", "B15"], "format": { "bold": true, "bgColor": "#D1FAE5" } },
    { "ids": ["A24"], "format": { "bold": true, "fontSize": 14, "bgColor": "#7C3AED", "fontColor": "#FFFFFF" } },
    { "ids": ["B24"], "format": { "bold": true, "fontSize": 14, "bgColor": "#EDE9FE" } }
  ]
},
{
  "tool": "create_cash_flow_forecast",
  "label": "cash flow forecast",
  "cells": {
    "A1": { "value": "Cash Flow Forecast" },
    "A3": { "value": "Month" },
    "B3": { "value": "Starting Balance" },
    "C3": { "value": "Inflows" },
    "D3": { "value": "Outflows" },
    "E3": { "value": "Net Cash Flow" },
    "F3": { "value": "Ending Balance" },
    "A4": { "value": "Jan" },
    "B4": { "value": 10000 },
    "C4": { "value": 25000 },
    "D4": { "value": 22000 },
    "E4": { "value": null, "formula": "=C4-D4" },
    "F4": { "value": null, "formula": "=B4+E4" },
    "A5": { "value": "Feb" },
    "B5": { "value": null, "formula": "=F4" },
    "C5": { "value": 22000 },
    "D5": { "value": 20000 },
    "E5": { "value": null, "formula": "=C5-D5" },
    "F5": { "value": null, "formula": "=B5+E5" },
    "A6": { "value": "Mar" },
    "B6": { "value": null, "formula": "=F5" },
    "C6": { "value": 28000 },
    "D6": { "value": 24000 },
    "E6": { "value": null, "formula": "=C6-D6" },
    "F6": { "value": null, "formula": "=B6+E6" },
    "A7": { "value": "Apr" },
    "B7": { "value": null, "formula": "=F6" },
    "C7": { "value": 20000 },
    "D7": { "value": 23000 },
    "E7": { "value": null, "formula": "=C7-D7" },
    "F7": { "value": null, "formula": "=B7+E7" },
    "A8": { "value": "May" },
    "B8": { "value": null, "formula": "=F7" },
    "C8": { "value": 30000 },
    "D8": { "value": 21000 },
    "E8": { "value": null, "formula": "=C8-D8" },
    "F8": { "value": null, "formula": "=B8+E8" },
    "A9": { "value": "Jun" },
    "B9": { "value": null, "formula": "=F8" },
    "C9": { "value": 26000 },
    "D9": { "value": 22000 },
    "E9": { "value": null, "formula": "=C9-D9" },
    "F9": { "value": null, "formula": "=B9+E9" }
  },
  "formats": [
    { "ids": ["A3", "B3", "C3", "D3", "E3", "F3"], "format": { "bold": true, "bgColor": "#7C3AED", "fontColor": "#FFFFFF", "textAlign": "center" } },
    { "ids": ["A1"], "format": { "bold": true, "fontSize": 16, "fontColor": "#7C3AED" } }
  ]
},
{
  "tool": "create_quarterly_tax_estimator",
  "label": "quarterly tax estimator",
  "cells": {
    "A1": { "value": "Quarterly Tax Estimator" },
    "A3": { "value": "Quarter" },
    "B3": { "value": "Gross Income" },
    "C3": { "value": "Deductions" },
    "D3": { "value": "Taxable Income" },
    "E3": { "value": "Est. Tax Rate" },
    "F3": { "value": "Tax Owed" },
    "A4": { "value": "Q1" },
    "B4": { "value": 32000 },
    "C4": { "value": 5200 },
    "D4": { "value": null, "formula": "=B4-C4" },
    "E4": { "value": 0.25 },
    "F4": { "value": null, "formula": "=D4*E4" },
    "A5": { "value": "Q2" },
    "B5": { "value": 38000 },
    "C5": { "value": 6100 },
    "D5": { "value": null, "formula": "=B5-C5" },
    "E5": { "value": 0.25 },
    "F5": { "value": null, "formula": "=D5*E5" },
    "A6": { "value": "Q3" },
    "B6": { "value": 29000 },
    "C6": { "value": 4800 },
    "D6": { "value": null, "formula": "=B6-C6" },
    "E6": { "value": 0.25 },
    "F6": { "value": null, "formula": "=D6*E6" },
    "A7": { "value": "Q4" },
    "B7": { "value": 41000 },
    "C7": { "value": 7200 },
    "D7": { "value": null, "formula": "=B7-C7" },
    "E7": { "value": 0.25 },
    "F7": { "value": null, "formula": "=D7*E7" },
    "A9": { "value": "ANNUAL TOTALS" },
    "B9": { "value": null, "formula": "=SUM(B4:B7)" },
    "C9": { "value": null, "formula": "=SUM(C4:C7)" },
    "D9": { "value": null, "formula": "=SUM(D4:D7)" },
    "F9": { "value": null, "formula": "=SUM(F4:F7)" }
  },
  "formats": [
    { "ids": ["A3", "B3", "C3", "D3", "E3", "F3"], "format": { "bold": true, "bgColor": "#7C3AED", "fontColor": "#FFFFFF", "textAlign": "center" } },
    { "ids": ["A1"], "format": { "bold": true, "fontSize": 16, "fontColor": "#7C3AED" } },
    { "ids": ["A9"], "format": { "bold": true } },
    { "ids": ["B9", "D9", "F9"], "format": { "bold": true, "bgColor": "#EDE9FE" } }
  ]
},
{
  "tool": "create_ar_aging",
  "label": "ar aging",
  "cells": {
    "A1": { "value": "Accounts Receivable Aging Report" },
    "A3": { "value": "Customer" },
    "B3": { "value": "Current" },
    "C3": { "value": "1-30 Days" },
    "D3": { "value": "31-60 Days" },
    "E3": { "value": "61-90 Days" },
    "F3": { "value": "90+ Days" },
    "G3": { "value": "Total" },
    "A4": { "value": "Acme Corp" },
    "B4": { "value": 4500 },
    "C4": { "value": 2200 },
    "D4": { "value": 0 },
    "E4": { "value": 0 },
    "F4": { "value": 0 },
    "G4": { "value": null, "formula": "=SUM(B4:F4)" },
    "A5": { "value": "Beta LLC" },
    "B5": { "value": 1200 },
    "C5": { "value": 3400 },
    "D5": { "value": 1800 },
    "E5": { "value": 0 },
    "F5": { "value": 0 },
    "G5": { "value": null, "formula": "=SUM(B5:F5)" },
    "A6": { "value": "Gamma Inc" },
    "B6": { "value": 0 },
    "C6": { "value": 0 },
    "D6": { "value": 2500 },
    "E6": { "value": 4100 },
    "F6": { "value": 1500 },
    "G6": { "value": null, "formula": "=SUM(B6:F6)" },
    "A7": { "value": "Delta Co" },
    "B7": { "value": 6000 },
    "C7": { "value": 0 },
    "D7": { "value": 0 },
    "E7": { "value": 0 },
    "F7": { "value": 0 },
    "G7": { "value": null, "formula": "=SUM(B7:F7)" },
    "A9": { "value": "TOTALS" },
    "B9": { "value": null, "formula": "=SUM(B4:B7)" },
    "C9": { "value": null, "formula": "=SUM(C4:C7)" },
    "D9": { "value": null, "formula": "=SUM(D4:D7)" },
    "E9": { "value": null, "formula": "=SUM(E4:E7)" },
    "F9": { "value": null, "formula": "=SUM(F4:F7)" },
    "G9": { "value": null, "formula": "=SUM(G4:G7)" }
  },
  "formats": [
    { "ids": ["A3", "B3", "C3", "D3", "E3", "F3", "G3"], "format": { "bold": true, "bgColor": "#7C3AED", "fontColor": "#FFFFFF", "textAlign": "center" } },
    { "ids": ["A1"], "format": { "bold": true, "fontSize": 16, "fontColor": "#7C3AED" } },
    { "ids": ["A9"], "format": { "bold": true } },
    { "ids": ["B9", "C9", "D9", "E9", "F9", "G9"], "format": { "bold": true, "bgColor": "#EDE9FE" } }
  ]
},
{
  "tool": "create_break_even_analysis",
  "label": "break-even analysis",
  "cells": {
    "A1": { "value": "Break-Even Analysis" },
    "A3": { "value": "Fixed Costs (monthly)" },
    "B3": { "value": 8500 },
    "A4": { "value": "Variable Cost per Unit" },
    "B4": { "value": 22 },
    "A5": { "value": "Selling Price per Unit" },
    "B5": { "value": 55 },
    "A7": { "value": "Contribution Margin" },
    "B7": { "value": null, "formula": "=B5-B4" },
    "A8": { "value": "Break-Even Units" },
    "B8": { "value": null, "formula": "=B3/(B5-B4)" },
    "A9": { "value": "Break-Even Revenue" },
    "B9": { "value": null, "formula": "=B8*B5" },
    "A11": { "value": "Units Sold" },
    "B11": { "value": "Revenue" },
    "C11": { "value": "Total Cost" },
    "D11": { "value": "Profit/Loss" },
    "A12": { "value": 100 },
    "B12": { "value": null, "formula": "=A12*$B$5" },
    "C12": { "value": null, "formula": "=$B$3+(A12*$B$4)" },
    "D12": { "value": null, "formula": "=B12-C12" },
    "A13": { "value": 200 },
    "B13": { "value": null, "formula": "=A13*$B$5" },
    "C13": { "value": null, "formula": "=$B$3+(A13*$B$4)" },
    "D13": { "value": null, "formula": "=B13-C13" },
    "A14": { "value": 300 },
    "B14": { "value": null, "formula": "=A14*$B$5" },
    "C14": { "value": null, "formula": "=$B$3+(A14*$B$4)" },
    "D14": { "value": null, "formula": "=B14-C14" },
    "A15": { "value": 400 },
    "B15": { "value": null, "formula": "=A15*$B$5" },
    "C15": { "value": null, "formula": "=$B$3+(A15*$B$4)" },
    "D15": { "value": null, "formula": "=B15-C15" }
  },
  "formats": [
    { "ids": ["A1"], "format": { "bold": true, "fontSize": 16, "fontColor": "#7C3AED" } },
    { "ids": ["A3", "A4", "A5", "A7", "A8", "A9"], "format": { "bold": true } },
    { "ids": ["B7", "B8", "B9"], "format": { "bold": true, "bgColor": "#EDE9FE" } },
    { "ids": ["A11", "B11", "C11", "D11"], "format": { "bold": true, "bgColor": "#7C3AED", "fontColor": "#FFFFFF", "textAlign": "center" } }
  ]
},
{
  "tool": "create_business_expense_report",
  "label": "business expense report",
  "cells": {
    "A1": { "value": "Business Expense Report" },
    "A2": { "value": "Employee: __________" },
    "A4": { "value": "Date" },
    "B4": { "value": "Category" },
    "C4": { "value": "Description" },
    "D4": { "value": "Amount" },
    "E4": { "value": "Receipt" },
    "A5": { "value": "2024-03-01" },
    "B5": { "value": "Travel" },
    "C5": { "value": "Flight to client site" },
    "D5": { "value": 385 },
    "E5": { "value": "Yes" },
    "A6": { "value": "2024-03-01" },
    "B6": { "value": "Meals" },
    "C6": { "value": "Client dinner" },
    "D6": { "value": 72 },
    "E6": { "value": "Yes" },
    "A7": { "value": "2024-03-02" },
    "B7": { "value": "Lodging" },
    "C7": { "value": "Hotel (1 night)" },
    "D7": { "value": 189 },
    "E7": { "value": "Yes" },
    "A8": { "value": "2024-03-02" },
    "B8": { "value": "Transport" },
    "C8": { "value": "Uber to meeting" },
    "D8": { "value": 28 },
    "E8": { "value": "Yes" },
    "A9": { "value": "2024-03-03" },
    "B9": { "value": "Supplies" },
    "C9": { "value": "Presentation materials" },
    "D9": { "value": 45 },
    "E9": { "value": "No" },
    "A11": { "value": "TOTAL" },
    "D11": { "value": null, "formula": "=SUM(D5:D9)" }
  },
  "formats": [
    { "ids": ["A4", "B4", "C4", "D4", "E4"], "format": { "bold": true, "bgColor": "#7C3AED", "fontColor": "#FFFFFF", "textAlign": "center" } },
    { "ids": ["A1"], "format": { "bold": true, "fontSize": 16, "fontColor": "#7C3AED" } },
    { "ids": ["A11"], "format": { "bold": true } },
    { "ids": ["D11"], "format": { "bold": true, "bgColor": "#EDE9FE" } }
  ]
},
{
  "tool": "create_mileage_log",
  "label": "mileage log",
  "cells": {
    "A1": { "value": "Business Mileage Log" },
    "A2": { "value": "IRS Rate: $0.67/mile (2024)" },
    "A4": { "value": "Date" },
    "B4": { "value": "Destination" },
    "C4": { "value": "Purpose" },
    "D4": { "value": "Miles" },
    "E4": { "value": "Deduction" },
    "A5": { "value": "2024-01-05" },
    "B5": { "value": "Client office - Denver" },
    "C5": { "value": "Client meeting" },
    "D5": { "value": 42 },
    "E5": { "value": null, "formula": "=D5*0.67" },
    "A6": { "value": "2024-01-08" },
    "B6": { "value": "Office Depot" },
    "C6": { "value": "Supply pickup" },
    "D6": { "value": 12 },
    "E6": { "value": null, "formula": "=D6*0.67" },
    "A7": { "value": "2024-01-12" },
    "B7": { "value": "Conference center" },
    "C7": { "value": "Industry conference" },
    "D7": { "value": 68 },
    "E7": { "value": null, "formula": "=D7*0.67" },
    "A8": { "value": "2024-01-15" },
    "B8": { "value": "Bank branch" },
    "C8": { "value": "Business deposit" },
    "D8": { "value": 8 },
    "E8": { "value": null, "formula": "=D8*0.67" },
    "A9": { "value": "2024-01-19" },
    "B9": { "value": "Vendor warehouse" },
    "C9": { "value": "Inventory inspection" },
    "D9": { "value": 55 },
    "E9": { "value": null, "formula": "=D9*0.67" },
    "A11": { "value": "TOTALS" },
    "D11": { "value": null, "formula": "=SUM(D5:D9)" },
    "E11": { "value": null, "formula": "=SUM(E5:E9)" }
  },
  "formats": [
    { "ids": ["A4", "B4", "C4", "D4", "E4"], "format": { "bold": true, "bgColor": "#7C3AED", "fontColor": "#FFFFFF", "textAlign": "center" } },
    { "ids": ["A1"], "format": { "bold": true, "fontSize": 16, "fontColor": "#7C3AED" } },
    { "ids": ["A2"], "format": { "bold": false, "fontColor": "#6B7280" } },
    { "ids": ["A11"], "format": { "bold": true } },
    { "ids": ["D11", "E11"], "format": { "bold": true, "bgColor": "#EDE9FE" } }
  ]
},
{
  "tool": "create_annual_budget_vs_actual",
  "label": "annual budget vs actual",
  "cells": {
    "A1": { "value": "Annual Budget vs Actual" },
    "A3": { "value": "Category" },
    "B3": { "value": "Budget" },
    "C3": { "value": "Actual" },
    "D3": { "value": "Variance" },
    "E3": { "value": "% Variance" },
    "A4": { "value": "Revenue" },
    "B4": { "value": 500000 },
    "C4": { "value": 485000 },
    "D4": { "value": null, "formula": "=C4-B4" },
    "E4": { "value": null, "formula": "=D4/B4" },
    "A5": { "value": "Payroll" },
    "B5": { "value": 200000 },
    "C5": { "value": 210000 },
    "D5": { "value": null, "formula": "=C5-B5" },
    "E5": { "value": null, "formula": "=D5/B5" },
    "A6": { "value": "Rent & Utilities" },
    "B6": { "value": 48000 },
    "C6": { "value": 48000 },
    "D6": { "value": null, "formula": "=C6-B6" },
    "E6": { "value": null, "formula": "=D6/B6" },
    "A7": { "value": "Marketing" },
    "B7": { "value": 60000 },
    "C7": { "value": 72000 },
    "D7": { "value": null, "formula": "=C7-B7" },
    "E7": { "value": null, "formula": "=D7/B7" },
    "A8": { "value": "Software & Tools" },
    "B8": { "value": 24000 },
    "C8": { "value": 21500 },
    "D8": { "value": null, "formula": "=C8-B8" },
    "E8": { "value": null, "formula": "=D8/B8" },
    "A9": { "value": "Travel" },
    "B9": { "value": 18000 },
    "C9": { "value": 15200 },
    "D9": { "value": null, "formula": "=C9-B9" },
    "E9": { "value": null, "formula": "=D9/B9" },
    "A11": { "value": "TOTALS" },
    "B11": { "value": null, "formula": "=SUM(B4:B9)" },
    "C11": { "value": null, "formula": "=SUM(C4:C9)" },
    "D11": { "value": null, "formula": "=SUM(D4:D9)" }
  },
  "formats": [
    { "ids": ["A3", "B3", "C3", "D3", "E3"], "format": { "bold": true, "bgColor": "#7C3AED", "fontColor": "#FFFFFF", "textAlign": "center" } },
    { "ids": ["A1"], "format": { "bold": true, "fontSize": 16, "fontColor": "#7C3AED" } },
    { "ids": ["A11"], "format": { "bold": true } },
    { "ids": ["B11", "C11", "D11"], "format": { "bold": true, "bgColor": "#EDE9FE" } }
  ]
}
];
